#!/usr/bin/env bash
# This script installs and configures HAProxy to load balance between web-01 and web-02 using roundrobin

# Update and install HAProxy
sudo apt-get update -y
sudo apt-get install -y haproxy

# Configure HAProxy
sudo tee /etc/haproxy/haproxy.cfg > /dev/null <<EOF
global
    log /dev/log    local0
    log /dev/log    local1 notice
    chroot /var/lib/haproxy
    stats socket /run/haproxy/admin.sock mode 660 level admin
    stats timeout 30s
    user haproxy
    group haproxy
    daemon

defaults
    log     global
    mode    http
    option  httplog
    option  dontlognull
    timeout connect 10s
    timeout client  30s
    timeout server  30s

frontend fitsumtech
    bind *:80
    mode http
    default_backend app

backend app
    mode http
    balance roundrobin
    server web-01 54.196.148.122:80 check
    server web-02 54.163.26.229:80 check
EOF

# Restart HAProxy service
sudo systemctl restart haproxy
sudo systemctl enable haproxy
