#!/usr/bin/env bash
# This script installs and configures HAProxy for load balancing

sudo apt update
sudo apt install haproxy -y

sudo bash -c 'cat <<EOF > /etc/haproxy/haproxy.cfg
global
    log /dev/log local0
    log /dev/log local1 notice
    chroot /var/lib/haproxy
    stats socket /run/haproxy/admin.sock mode 660 level admin
    stats timeout 30s
    user haproxy
    group haproxy
    daemon

defaults
    log     global
    option  redispatch
    retries 3
    timeout http-request 10s
    timeout queue 1m
    timeout connect 10s
    timeout client 1m
    timeout server 1m
    timeout http-keep-alive 10s
    timeout check 10s

frontend http_front
    bind *:80
    stats uri /haproxy?stats
    default_backend http_back

backend http_back
    balance roundrobin
    server web01 54.196.148.122:80 check
    server web02 54.163.26.229:80 check
EOF'

sudo systemctl restart haproxy
sudo systemctl enable haproxy
